### ISSUE TITLE
dataset source

### ISSUE THREAD

**Issue by zperfet** [lucasayres/url-feature-extractor#1]
hello，where did you get your urls? download from phishtank website?

**Comment by lucasayres** [comment]
Hello @zperfet , both malicious and benign international URLs have been extracted from the repository: https://github.com/faizann24/Using-machine-learning-to-detect-malicious-URLs

This repository was made available in an article on malicious URL detection using machine learning, which was presented by the company Fsecurify.

The article tells how they got those URLs. The malicious URL data set was obtained through a scan of various sites that provide malicious links, such as http://vxvault.net. Benign URLs were obtained from a given link in a research paper.

**Comment by zperfet** [comment]
Hello， @lucasayres ，thanks for your reply. I switched to url
[https://github.com/faizann24/Using-machine-learning-to-detect-malicious-URLs](https://github.com/faizann24/Using-machine-learning-to-detect-malicious-URLs)
but i can not open the url http://fsecurify.com/using-machine-learning-detect-malicious-urls/,
instead i search the title of the url, and found a blog about it. It may be helpful to someone else:)
[https://www.kdnuggets.com/2016/10/machine-learning-detect-malicious-urls.html](https://www.kdnuggets.com/2016/10/machine-learning-detect-malicious-urls.html)
